binary_ensemble_models:
  class_models: { 1: "Class_1.onnx", 3: "Class_3.onnx", 4: "Class_4.onnx",
                  5: "Class_5.onnx", 6: "Class_6.onnx", 9: "Class_9.onnx",
                  12: "Class_12.onnx", 13: "Class_13.onnx", 14: "Class_14.onnx",
                  15: "Class_15.onnx" }
  boundary_model: "Class_bnd.onnx"
  ped_model: "Class_4PED.onnx"
  three_and_six_model: "Class_3and6.onnx"
  tr_model: "Class_tr.onnx"
  catboost_model: "catboost_model.onnx"
  output_object_name: 'Tissue'
  output_object_short_name: 'T'
  preload: false
  batch_size: 4
  input_size: [1, 512, 512]
  channels_axis: 0
  channels_order: 'rgb'
  normalize: false
  mask_binarization_threshold: 0.5
