keypoint_model:
  file_name: 'Keypoints.onnx'
  input_height: 256
  input_width: 512
  longest_max_size: 512
  normalize_mean: 0.5
  normalize_std: 0.5
  normalize_max_pixel_value: 255.0
  keypoint_radius: 3
